model_list:
  - model_name: llama3.2:1b
    litellm_params:
      model: ollama/llama3.2:1b
      api_base: "http://ollama:11434"
  - model_name: qwen2.5:1.5b
    litellm_params:
      model: ollama/qwen2.5:1.5b
      api_base: "http://ollama:11434"
  - model_name: moondream
    litellm_params:
      model: ollama/moondream
      api_base: "http://ollama:11434"
  - model_name: qwen3-vl:2b
    litellm_params:
      model: ollama/qwen3-vl:2b
      api_base: "http://ollama:11434"
